### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by blackrulz** [BreakfastCraft/DelusionsOfAdequacy#4]
nei was not loading, after restart the world load stops.

http://pastebin.com/FwFYghuf

**Comment by blackrulz** [comment]
new world gen is ok, but nei is not loading at all :(

**Comment by demethan** [comment]
What version of notenoughitem does DoA install.  I think I might have forgotten to downgrade the version on the pack.

**Comment by demethan** [comment]
Ok. .I fixed it.
